<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice Rule</name>
  <uuid>8b611454-2054-4746-a6cc-f3b965e7e85d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined
then
	set decision to "Hello " + Name + "! " + 'Weather Advice' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
