<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c599432b-259d-4a33-968c-a639f19cff8a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, we dont have enough information to provide a response" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
